-- Seeds pour les traductions des personnages
-- Traductions FR et EN pour chaque personnage avec armes

-- Geralt de Riv
INSERT INTO character_translations (character_id, language_code, name, role, description, biography, weapons) VALUES
('770e8400-e29b-41d4-a716-446655440001', 'fr', 'Geralt de Riv', 'Protagoniste', 'Le Sorceleur légendaire, chasseur de monstres professionnel aux cheveux blancs et aux yeux de chat.', 'Geralt de Riv est un sorceleur, un chasseur de monstres mutant qui parcourt le Continent en quête de contrats. Formé dès l''enfance à Kaer Morhen, il a subi les mutations qui lui confèrent des capacités surhumaines. Connu sous le nom de "Boucher de Blaviken", il est l''un des derniers sorceleurs encore en vie.', 'Épée d''acier (contre les humains), Épée d''argent (contre les monstres), Arbalète, Bombes alchimiques, Signes magiques (Aard, Igni, Yrden, Quen, Axii)'),
('770e8400-e29b-41d4-a716-446655440001', 'en', 'Geralt of Rivia', 'Protagonist', 'The legendary Witcher, a professional monster hunter with white hair and cat-like eyes.', 'Geralt of Rivia is a witcher, a mutant monster hunter who travels the Continent seeking contracts. Trained from childhood at Kaer Morhen, he underwent mutations that grant him superhuman abilities. Known as the "Butcher of Blaviken", he is one of the last witchers still alive.', 'Steel sword (against humans), Silver sword (against monsters), Crossbow, Alchemical bombs, Magic signs (Aard, Igni, Yrden, Quen, Axii)'),

-- Yennefer
('770e8400-e29b-41d4-a716-446655440002', 'fr', 'Yennefer de Vengerberg', 'Magicienne', 'Puissante magicienne aux yeux violets, conseillère du roi Demavend et amante de Geralt.', 'Yennefer de Vengerberg est l''une des magiciennes les plus puissantes du Continent. Née bossue, elle a été transformée par la magie en une beauté envoûtante. Elle entretient une relation tumultueuse avec Geralt et considère Ciri comme sa fille adoptive.', 'Magie du chaos, Portails dimensionnels, Sorts offensifs (foudre, feu), Nécromancie, Télépathie'),
('770e8400-e29b-41d4-a716-446655440002', 'en', 'Yennefer of Vengerberg', 'Sorceress', 'Powerful violet-eyed sorceress, advisor to King Demavend and Geralt''s lover.', 'Yennefer of Vengerberg is one of the most powerful sorceresses on the Continent. Born a hunchback, she was transformed by magic into an enchanting beauty. She maintains a tumultuous relationship with Geralt and considers Ciri her adoptive daughter.', 'Chaos magic, Dimensional portals, Offensive spells (lightning, fire), Necromancy, Telepathy'),

-- Ciri
('770e8400-e29b-41d4-a716-446655440003', 'fr', 'Cirilla Fiona Elen Riannon', 'Protagoniste', 'Princesse de Cintra dotée du Sang Ancien, fille adoptive de Geralt et Yennefer.', 'Ciri est la princesse héritière de Cintra et possède le Sang Ancien, lui conférant des pouvoirs de voyage entre les mondes. Après la chute de Cintra, elle devient la fille adoptive de Geralt qui l''entraîne aux arts du combat à Kaer Morhen.', 'Épée de sorceleur, Pouvoirs du Sang Ancien (téléportation, voyage dimensionnel), Techniques de combat de Kaer Morhen'),
('770e8400-e29b-41d4-a716-446655440003', 'en', 'Cirilla Fiona Elen Riannon', 'Protagonist', 'Princess of Cintra with Elder Blood, adoptive daughter of Geralt and Yennefer.', 'Ciri is the crown princess of Cintra and possesses the Elder Blood, granting her powers to travel between worlds. After Cintra''s fall, she becomes Geralt''s adoptive daughter who trains her in combat at Kaer Morhen.', 'Witcher sword, Elder Blood powers (teleportation, dimensional travel), Kaer Morhen combat techniques'),

-- V
('770e8400-e29b-41d4-a716-446655440004', 'fr', 'V', 'Protagoniste', 'Mercenaire de Night City en quête de l''implant qui pourrait lui offrir l''immortalité.', 'V est un mercenaire personnalisable vivant dans la mégalopole dystopique de Night City. Après un braquage qui tourne mal, V se retrouve avec une puce contenant la conscience de Johnny Silverhand dans sa tête, et doit trouver un moyen de survivre.', 'Armes à feu (pistolets, fusils, mitraillettes), Cyberware (mantis blades, gorilla arms, monowire), Quickhacks, Katanas, Grenades'),
('770e8400-e29b-41d4-a716-446655440004', 'en', 'V', 'Protagonist', 'Night City mercenary seeking the implant that could grant immortality.', 'V is a customizable mercenary living in the dystopian megacity of Night City. After a heist gone wrong, V ends up with a chip containing Johnny Silverhand''s consciousness in their head, and must find a way to survive.', 'Firearms (pistols, rifles, SMGs), Cyberware (mantis blades, gorilla arms, monowire), Quickhacks, Katanas, Grenades'),

-- Johnny Silverhand
('770e8400-e29b-41d4-a716-446655440005', 'fr', 'Johnny Silverhand', 'Deutéragoniste', 'Rockerboy légendaire et terroriste anti-corporatiste, dont la conscience est piégée dans une puce.', 'Johnny Silverhand était le leader du groupe Samurai et un révolutionnaire notoire. Après avoir attaqué la tour Arasaka en 2023, sa conscience a été numérisée. Des décennies plus tard, il se retrouve dans la tête de V, formant une alliance improbable.', 'Malorian Arms 3516 (pistolet iconique), Bras cybernétique argenté, Guitare électrique'),
('770e8400-e29b-41d4-a716-446655440005', 'en', 'Johnny Silverhand', 'Deuteragonist', 'Legendary rockerboy and anti-corporate terrorist whose consciousness is trapped in a chip.', 'Johnny Silverhand was the leader of the band Samurai and a notorious revolutionary. After attacking Arasaka Tower in 2023, his consciousness was digitized. Decades later, he finds himself in V''s head, forming an unlikely alliance.', 'Malorian Arms 3516 (iconic pistol), Silver cybernetic arm, Electric guitar'),

-- Kratos
('770e8400-e29b-41d4-a716-446655440006', 'fr', 'Kratos', 'Protagoniste', 'Ancien dieu de la guerre grec, maintenant père protecteur dans les terres nordiques.', 'Kratos est un guerrier spartiate devenu le Dieu de la Guerre après avoir tué Arès. Ayant détruit le panthéon olympien, il s''est exilé dans les royaumes nordiques où il élève son fils Atreus tout en cachant son passé sanglant.', 'Hache Léviathan (enchantée par la glace), Lames du Chaos (chaînes enflammées), Bouclier Gardien, Rage Spartiate'),
('770e8400-e29b-41d4-a716-446655440006', 'en', 'Kratos', 'Protagonist', 'Former Greek God of War, now a protective father in the Norse lands.', 'Kratos is a Spartan warrior who became the God of War after killing Ares. Having destroyed the Olympian pantheon, he exiled himself to the Norse realms where he raises his son Atreus while hiding his bloody past.', 'Leviathan Axe (ice-enchanted), Blades of Chaos (flaming chains), Guardian Shield, Spartan Rage'),

-- Atreus
('770e8400-e29b-41d4-a716-446655440007', 'fr', 'Atreus', 'Deutéragoniste', 'Fils de Kratos et Faye, jeune archer découvrant son héritage divin.', 'Atreus est le fils de Kratos et de la géante Faye. Élevé dans l''ignorance de ses origines divines, il accompagne son père dans un voyage pour disperser les cendres de sa mère, découvrant progressivement sa véritable nature.', 'Arc de Talon, Flèches élémentaires (lumière, choc, soniques), Invocations runiques, Transformation en loup (Ragnarök)'),
('770e8400-e29b-41d4-a716-446655440007', 'en', 'Atreus', 'Deuteragonist', 'Son of Kratos and Faye, young archer discovering his divine heritage.', 'Atreus is the son of Kratos and the giantess Faye. Raised unaware of his divine origins, he accompanies his father on a journey to scatter his mother''s ashes, gradually discovering his true nature.', 'Talon Bow, Elemental arrows (light, shock, sonic), Runic summons, Wolf transformation (Ragnarök)'),

-- Aloy
('770e8400-e29b-41d4-a716-446655440008', 'fr', 'Aloy', 'Protagoniste', 'Chasseuse de machines exilée, découvrant les secrets d''un monde post-apocalyptique.', 'Aloy est une paria de la tribu Nora, élevée par l''exilé Rost. Dotée d''un Focus lui permettant d''analyser les machines, elle part en quête de ses origines et découvre qu''elle est le clone d''Elisabet Sobeck, la scientifique qui a sauvé la vie sur Terre.', 'Arc de chasseur, Lance, Fronde à bombes, Lanceur de disques, Pièges et fils-pièges, Focus (dispositif d''analyse)'),
('770e8400-e29b-41d4-a716-446655440008', 'en', 'Aloy', 'Protagonist', 'Exiled machine hunter, uncovering the secrets of a post-apocalyptic world.', 'Aloy is an outcast from the Nora tribe, raised by the exile Rost. Equipped with a Focus that allows her to analyze machines, she sets out to find her origins and discovers she is a clone of Elisabet Sobeck, the scientist who saved life on Earth.', 'Hunter Bow, Spear, Blast Sling, Disc Launcher, Traps and tripwires, Focus (analysis device)'),

-- Arthur Morgan
('770e8400-e29b-41d4-a716-446655440009', 'fr', 'Arthur Morgan', 'Protagoniste', 'Hors-la-loi loyal du gang Van der Linde, tiraillé entre loyauté et rédemption.', 'Arthur Morgan est le bras droit de Dutch Van der Linde et membre du gang depuis son enfance. Alors que le gang fuit vers l''ouest après un braquage raté, Arthur commence à remettre en question ses choix de vie et cherche la rédemption.', 'Revolvers (Cattleman, Schofield), Fusils à répétition, Fusil de chasse, Arc, Couteau de chasse, Lasso'),
('770e8400-e29b-41d4-a716-446655440009', 'en', 'Arthur Morgan', 'Protagonist', 'Loyal outlaw of the Van der Linde gang, torn between loyalty and redemption.', 'Arthur Morgan is Dutch Van der Linde''s right-hand man and has been a gang member since childhood. As the gang flees west after a botched robbery, Arthur begins to question his life choices and seeks redemption.', 'Revolvers (Cattleman, Schofield), Repeaters, Shotgun, Bow, Hunting knife, Lasso'),

-- John Marston
('770e8400-e29b-41d4-a716-446655440010', 'fr', 'John Marston', 'Deutéragoniste', 'Ancien hors-la-loi cherchant à construire une vie honnête pour sa famille.', 'John Marston est un ancien membre du gang Van der Linde qui tente de se racheter. Après les événements du gang, il essaie de construire une vie paisible avec sa femme Abigail et son fils Jack dans leur ranch de Beecher''s Hope.', 'Revolvers, Fusils à répétition, Fusil de chasse, Couteau, Lasso, Dead Eye'),
('770e8400-e29b-41d4-a716-446655440010', 'en', 'John Marston', 'Deuteragonist', 'Former outlaw seeking to build an honest life for his family.', 'John Marston is a former Van der Linde gang member trying to redeem himself. After the gang''s events, he attempts to build a peaceful life with his wife Abigail and son Jack at their Beecher''s Hope ranch.', 'Revolvers, Repeaters, Shotgun, Knife, Lasso, Dead Eye'),

-- Melina
('770e8400-e29b-41d4-a716-446655440011', 'fr', 'Melina', 'Alliée', 'Mystérieuse jeune femme offrant un accord au Sans-Éclat pour atteindre l''Arbre-Monde.', 'Melina est une énigmatique jeune femme qui propose au Sans-Éclat de devenir sa Vierge aux Doigts. Elle guide le joueur vers l''Arbre-Monde et possède une connexion mystérieuse avec la Rune de la Mort et Marika.', 'Dague, Incantations de la Flamme Noire, Épée courte'),
('770e8400-e29b-41d4-a716-446655440011', 'en', 'Melina', 'Ally', 'Mysterious young woman offering a deal to the Tarnished to reach the Erdtree.', 'Melina is an enigmatic young woman who offers to become the Tarnished''s Finger Maiden. She guides the player toward the Erdtree and has a mysterious connection to the Rune of Death and Marika.', 'Dagger, Black Flame incantations, Short sword'),

-- Ranni
('770e8400-e29b-41d4-a716-446655440012', 'fr', 'Ranni la Sorcière', 'Alliée', 'Empyrée rebelle ayant rejeté son destin pour forger son propre chemin.', 'Ranni est une Empyrée, fille de Rennala et Radagon. Elle a orchestré la Nuit des Couteaux Noirs pour se libérer de l''influence des Doigts Supérieurs et poursuit un plan pour créer un nouvel ordre dans l''Entre-Terre.', 'Magie lunaire de Caria, Lune Noire de Ranni, Invocations spectrales'),
('770e8400-e29b-41d4-a716-446655440012', 'en', 'Ranni the Witch', 'Ally', 'Rebellious Empyrean who rejected her fate to forge her own path.', 'Ranni is an Empyrean, daughter of Rennala and Radagon. She orchestrated the Night of the Black Knives to free herself from the Greater Will''s influence and pursues a plan to create a new order in the Lands Between.', 'Carian moon magic, Ranni''s Dark Moon, Spectral summons'),

-- Zagreus
('770e8400-e29b-41d4-a716-446655440013', 'fr', 'Zagreus', 'Protagoniste', 'Prince des Enfers cherchant à s''échapper pour retrouver sa mère Perséphone.', 'Zagreus est le fils d''Hadès et de Perséphone. Découvrant que sa mère a quitté les Enfers, il tente inlassablement de s''échapper du royaume de son père, aidé par les dieux de l''Olympe et les habitants de la Maison d''Hadès.', 'Stygius (épée infernale), Coronacht (arc), Aegis (bouclier), Varatha (lance), Exagryph (rail), Malphon (gantelets), Bénédictions olympiennes'),
('770e8400-e29b-41d4-a716-446655440013', 'en', 'Zagreus', 'Protagonist', 'Prince of the Underworld seeking to escape to find his mother Persephone.', 'Zagreus is the son of Hades and Persephone. Discovering that his mother left the Underworld, he tirelessly attempts to escape his father''s realm, aided by the Olympian gods and the denizens of the House of Hades.', 'Stygius (infernal blade), Coronacht (bow), Aegis (shield), Varatha (spear), Exagryph (rail), Malphon (fists), Olympian boons'),

-- Megaera
('770e8400-e29b-41d4-a716-446655440014', 'fr', 'Mégère', 'Boss / Alliée', 'L''une des trois Furies, gardienne du Tartare et ancienne amante de Zagreus.', 'Mégère est l''une des trois sœurs Furies chargées de punir les mortels. Elle garde le Tartare et affronte Zagreus lors de ses tentatives d''évasion, bien qu''ils partagent une histoire romantique complexe.', 'Fouet de Furie, Projectiles d''ombre, Invocation de sbires'),
('770e8400-e29b-41d4-a716-446655440014', 'en', 'Megaera', 'Boss / Ally', 'One of the three Furies, guardian of Tartarus and Zagreus'' former lover.', 'Megaera is one of the three Fury sisters tasked with punishing mortals. She guards Tartarus and confronts Zagreus during his escape attempts, though they share a complex romantic history.', 'Fury whip, Shadow projectiles, Minion summoning'),

-- Jin Sakai
('770e8400-e29b-41d4-a716-446655440015', 'fr', 'Jin Sakai', 'Protagoniste', 'Samouraï devenant le Fantôme pour libérer Tsushima de l''invasion mongole.', 'Jin Sakai est l''un des derniers samouraïs survivants après l''invasion mongole de Tsushima en 1274. Pour sauver son île, il abandonne le code du bushido et adopte des tactiques de guérilla, devenant une légende connue sous le nom de Fantôme.', 'Katana Sakai, Tanto, Arc long et demi-arc, Kunai, Bombes fumigènes, Bombes collantes, Cloches de vent'),
('770e8400-e29b-41d4-a716-446655440015', 'en', 'Jin Sakai', 'Protagonist', 'Samurai becoming the Ghost to liberate Tsushima from the Mongol invasion.', 'Jin Sakai is one of the last surviving samurai after the Mongol invasion of Tsushima in 1274. To save his island, he abandons the bushido code and adopts guerrilla tactics, becoming a legend known as the Ghost.', 'Sakai Katana, Tanto, Longbow and half bow, Kunai, Smoke bombs, Sticky bombs, Wind chimes'),

-- Ellie
('770e8400-e29b-41d4-a716-446655440016', 'fr', 'Ellie', 'Protagoniste', 'Survivante immunisée au Cordyceps, en quête de vengeance dans un monde dévasté.', 'Ellie est une jeune femme immunisée au champignon Cordyceps qui a ravagé l''humanité. Après avoir traversé le pays avec Joel, elle vit dans la communauté de Jackson. Un événement tragique la lance dans une quête de vengeance impitoyable.', 'Pistolet, Fusil de chasse, Arc, Couteau à cran d''arrêt, Cocktails Molotov, Bombes artisanales, Mines'),
('770e8400-e29b-41d4-a716-446655440016', 'en', 'Ellie', 'Protagonist', 'Cordyceps-immune survivor on a quest for vengeance in a devastated world.', 'Ellie is a young woman immune to the Cordyceps fungus that ravaged humanity. After crossing the country with Joel, she lives in the Jackson community. A tragic event sends her on a ruthless quest for vengeance.', 'Pistol, Shotgun, Bow, Switchblade, Molotov cocktails, Pipe bombs, Mines'),

-- Joel
('770e8400-e29b-41d4-a716-446655440017', 'fr', 'Joel Miller', 'Deutéragoniste', 'Survivant endurci devenu figure paternelle pour Ellie.', 'Joel Miller est un survivant texan qui a perdu sa fille Sarah lors de l''épidémie. Vingt ans plus tard, il est chargé d''escorter Ellie à travers le pays, développant un lien paternel qui le pousse à des choix moralement ambigus.', 'Revolver, Fusil de chasse, Fusil de chasse à pompe, Armes de mêlée improvisées (tuyaux, battes), Cocktails Molotov, Bombes à clous'),
('770e8400-e29b-41d4-a716-446655440017', 'en', 'Joel Miller', 'Deuteragonist', 'Hardened survivor who became a father figure to Ellie.', 'Joel Miller is a Texan survivor who lost his daughter Sarah during the outbreak. Twenty years later, he is tasked with escorting Ellie across the country, developing a paternal bond that drives him to morally ambiguous choices.', 'Revolver, Hunting rifle, Pump shotgun, Improvised melee weapons (pipes, bats), Molotov cocktails, Nail bombs')
ON CONFLICT (character_id, language_code) DO UPDATE SET
  name = EXCLUDED.name,
  role = EXCLUDED.role,
  description = EXCLUDED.description,
  biography = EXCLUDED.biography,
  weapons = EXCLUDED.weapons;
