import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { resolve } from "path";

/**
 * Two-project setup: "node" for pure logic tests (no jsdom overhead),
 * "dom" for tests that need a browser environment (React rendering, hooks).
 */

// Hook tests that use renderHook from @testing-library/react
const HOOK_TESTS_NEEDING_DOM = [
  "src/hooks/__tests__/useAdminCharacters.test.ts",
  "src/hooks/__tests__/useAdminCompanies.test.ts",
  "src/hooks/__tests__/useAdminGenres.test.ts",
  "src/hooks/__tests__/useAdminLanguages.test.ts",
  "src/hooks/__tests__/useCharacterForm.test.ts",
  "src/hooks/__tests__/useCollectionDetail.test.ts",
  "src/hooks/__tests__/useCollections.test.ts",
  "src/hooks/__tests__/useCompanyForm.test.ts",
  "src/hooks/__tests__/useGenreForm.test.ts",
  "src/hooks/__tests__/useLanguageForm.test.ts",
  "src/hooks/__tests__/useProfile.test.ts",
  "src/hooks/__tests__/useRecommendations.test.ts",
  "src/hooks/__tests__/usePersonalRecommendations.test.ts",
  "src/hooks/__tests__/use-toast.test.ts",
  "src/hooks/__tests__/usePriceHistory.test.ts",
  "src/hooks/__tests__/useSearchOverlay.test.ts",
  "src/hooks/__tests__/usePendingRequestCount.test.ts",
  "src/hooks/__tests__/useAchievements.test.ts",
  "src/hooks/__tests__/useAdminAchievements.test.ts",
  "src/hooks/__tests__/usePlayerAchievementManager.test.ts",
  "src/hooks/__tests__/useDiscussions.test.ts",
  "src/hooks/__tests__/useUnreadCount.test.ts",
  "src/hooks/__tests__/useCropEditor.test.ts",
  "src/hooks/__tests__/useImageUpload.test.ts",
  "src/hooks/__tests__/useAdminGames.test.ts",
  "src/hooks/__tests__/useBackgroundSync.test.ts",
  "src/hooks/__tests__/usePlayerReviews.test.ts",
  "src/hooks/__tests__/usePlayerPosts.test.ts",
  "src/hooks/__tests__/usePlayerCollections.test.ts",
  "src/hooks/__tests__/usePlayerActivity.test.ts",
  "src/hooks/__tests__/usePlayerPlaytime.test.ts",
  "src/hooks/__tests__/usePlayerSessions.test.ts",
  "src/hooks/__tests__/useDebouncedValue.test.ts",
  "src/hooks/__tests__/useDashboard.test.ts",
  "src/hooks/__tests__/useLocaleManager.test.ts",
  "src/hooks/__tests__/useGameDetails.test.ts",
  "src/hooks/__tests__/useGameAccent.test.ts",
  "src/hooks/__tests__/useEditorialRailState.test.ts",
  "src/hooks/__tests__/useCharacterFilters.test.ts",
  "src/hooks/__tests__/useReviews.test.ts",
  "src/hooks/__tests__/useComments.test.ts",
  "src/hooks/__tests__/useGameSync.test.ts",
  "src/hooks/__tests__/useCharacterSync.test.ts",
  "src/hooks/__tests__/useCharacterOverrides.test.ts",
  "src/hooks/__tests__/useGameListing.test.ts",
  "src/hooks/__tests__/useGenderForm.test.ts",
  "src/hooks/__tests__/useRatingForm.test.ts",
  "src/hooks/__tests__/useRatingSystemForm.test.ts",
  "src/hooks/__tests__/useRoleForm.test.ts",
  "src/hooks/__tests__/useSpeciesForm.test.ts",
  "src/hooks/__tests__/useTranslations.test.ts",
  "src/hooks/__tests__/useGameForm.test.ts",
  "src/hooks/__tests__/useAdminTranslations.test.ts",
  "src/hooks/__tests__/useFriends.test.ts",
  "src/hooks/__tests__/useLibraryGames.test.ts",
  "src/hooks/__tests__/useFriendRelationship.test.ts",
  "src/hooks/__tests__/useEntityLibraryToggle.test.ts",
  "src/hooks/__tests__/useEntityCharacterFavorite.test.ts",
  "src/hooks/__tests__/useCollectionMutations.test.ts",
  "src/hooks/__tests__/useCharacters.test.ts",
  "src/hooks/__tests__/usePostImageUpload.test.ts",
  "src/hooks/__tests__/useMentionAutocomplete.test.ts",
  "src/hooks/__tests__/useInView.test.ts",
  "src/hooks/__tests__/use-error-boundary.test.ts",
  "src/hooks/__tests__/useWebhookEvents.test.ts",
  "src/hooks/__tests__/useWebhookRegistrations.test.ts",
  "src/__tests__/setup.test.ts",
  "src/hooks/__tests__/useAdminComments.test.ts",
  "src/hooks/__tests__/useAdminDescriptors.test.ts",
  "src/hooks/__tests__/useAdminGenders.test.ts",
  "src/hooks/__tests__/useAdminPlatforms.test.ts",
  "src/hooks/__tests__/useAdminRatings.test.ts",
  "src/hooks/__tests__/useAdminRatingSystems.test.ts",
  "src/hooks/__tests__/useAdminReviews.test.ts",
  "src/hooks/__tests__/useAdminRoles.test.ts",
  "src/hooks/__tests__/useAdminSimilarGames.test.ts",
  "src/hooks/__tests__/useAdminSpecies.test.ts",
  "src/hooks/__tests__/useNotifications.test.ts",
  "src/hooks/__tests__/usePostComments.test.ts",
  "src/hooks/__tests__/useSubscribedFeed.test.ts",
];

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
    },
  },
  test: {
    globals: true,
    css: false,
    reporters: ["default"],
    exclude: ["test/e2e/**", "node_modules/**"],
    onConsoleLog: () => false,
    server: {
      deps: {
        inline: ["zod"],
      },
    },
    projects: [
      {
        extends: true,
        test: {
          name: "dom",
          environment: "jsdom",
          setupFiles: ["./test/setup-vitest.ts"],
          include: ["src/**/__tests__/*.test.tsx", ...HOOK_TESTS_NEEDING_DOM],
        },
      },
      {
        extends: true,
        test: {
          name: "node",
          environment: "node",
          include: [
            "src/**/__tests__/*.test.ts",
            "scripts/__tests__/*.test.ts",
            "test/integration/**/*.test.ts",
            "test/scripts/**/*.test.ts",
          ],
          exclude: HOOK_TESTS_NEEDING_DOM,
        },
      },
    ],
  },
});
