import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { resolve } from "path";

/**
 * Two-project setup: "node" for pure logic tests (no jsdom overhead),
 * "dom" for tests that need a browser environment (React rendering, hooks).
 */

// Hook tests that use renderHook from @testing-library/react
const HOOK_TESTS_NEEDING_DOM = [
  "test/unit/hooks/useAdminCharacters.test.ts",
  "test/unit/hooks/useAdminCompanies.test.ts",
  "test/unit/hooks/useAdminGenres.test.ts",
  "test/unit/hooks/useAdminLanguages.test.ts",
  "test/unit/hooks/useCharacterForm.test.ts",
  "test/unit/hooks/useCollectionDetail.test.ts",
  "test/unit/hooks/useCollections.test.ts",
  "test/unit/hooks/useCompanyForm.test.ts",
  "test/unit/hooks/useGenreForm.test.ts",
  "test/unit/hooks/useLanguageForm.test.ts",
  "test/unit/hooks/useProfile.test.ts",
  "test/unit/hooks/useRecommendations.test.ts",
  "test/unit/hooks/usePersonalRecommendations.test.ts",
  "test/unit/hooks/use-toast.test.ts",
  "test/unit/hooks/usePriceHistory.test.ts",
  "test/unit/hooks/useSearchOverlay.test.ts",
  "test/unit/hooks/usePendingRequestCount.test.ts",
  "test/unit/hooks/useAchievements.test.ts",
  "test/unit/hooks/useAdminAchievements.test.ts",
  "test/unit/hooks/usePlayerAchievementManager.test.ts",
  "test/unit/hooks/useDiscussions.test.ts",
  "test/unit/hooks/useUnreadCount.test.ts",
  "test/unit/hooks/useCropEditor.test.ts",
  "test/unit/hooks/useImageUpload.test.ts",
  "test/unit/hooks/useAdminGames.test.ts",
  "test/unit/hooks/useBackgroundSync.test.ts",
  "test/unit/hooks/usePlayerReviews.test.ts",
  "test/unit/hooks/usePlayerPosts.test.ts",
  "test/unit/hooks/usePlayerCollections.test.ts",
  "test/unit/hooks/usePlayerActivity.test.ts",
  "test/unit/hooks/usePlayerPlaytime.test.ts",
  "test/unit/hooks/useDebouncedValue.test.ts",
  "test/unit/hooks/useDashboard.test.ts",
  "test/unit/hooks/useLocaleManager.test.ts",
  "test/unit/hooks/useGameDetails.test.ts",
  "test/unit/hooks/useCharacterFilters.test.ts",
  "test/unit/hooks/useReviews.test.ts",
  "test/unit/hooks/useComments.test.ts",
  "test/unit/hooks/useGameSync.test.ts",
  "test/unit/hooks/useCharacterSync.test.ts",
  "test/unit/hooks/useCharacterOverrides.test.ts",
  "test/unit/hooks/useGameListing.test.ts",
  "test/unit/hooks/useGenderForm.test.ts",
  "test/unit/hooks/useRatingForm.test.ts",
  "test/unit/hooks/useRatingSystemForm.test.ts",
  "test/unit/hooks/useRoleForm.test.ts",
  "test/unit/hooks/useSpeciesForm.test.ts",
  "test/unit/hooks/useTranslations.test.ts",
  "test/unit/hooks/useGameForm.test.ts",
  "test/unit/hooks/useAdminTranslations.test.ts",
  "test/unit/hooks/useFriends.test.ts",
  "test/unit/hooks/useLibraryGames.test.ts",
  "test/unit/hooks/useFriendRelationship.test.ts",
  "test/unit/hooks/useEntityLibraryToggle.test.ts",
  "test/unit/hooks/useEntityCharacterFavorite.test.ts",
  "test/unit/hooks/useCollectionMutations.test.ts",
  "test/unit/hooks/useCharacters.test.ts",
  "test/unit/hooks/usePostImageUpload.test.ts",
  "test/unit/hooks/useMentionAutocomplete.test.ts",
  "test/unit/hooks/useInView.test.ts",
  "test/unit/hooks/use-error-boundary.test.ts",
  "test/unit/hooks/useWebhookEvents.test.ts",
  "test/unit/hooks/useWebhookRegistrations.test.ts",
  "test/setup.test.ts",
  "test/unit/hooks/useAdminComments.test.ts",
  "test/unit/hooks/useAdminDescriptors.test.ts",
  "test/unit/hooks/useAdminGenders.test.ts",
  "test/unit/hooks/useAdminPlatforms.test.ts",
  "test/unit/hooks/useAdminRatings.test.ts",
  "test/unit/hooks/useAdminRatingSystems.test.ts",
  "test/unit/hooks/useAdminReviews.test.ts",
  "test/unit/hooks/useAdminRoles.test.ts",
  "test/unit/hooks/useAdminSimilarGames.test.ts",
  "test/unit/hooks/useAdminSpecies.test.ts",
  "test/unit/hooks/useNotifications.test.ts",
  "test/unit/hooks/usePostComments.test.ts",
];

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
    },
  },
  test: {
    globals: true,
    css: false,
    reporters: ["default"],
    exclude: ["test/e2e/**", "node_modules/**"],
    onConsoleLog: () => false,
    server: {
      deps: {
        inline: ["zod"],
      },
    },
    projects: [
      {
        extends: true,
        test: {
          name: "dom",
          environment: "jsdom",
          setupFiles: ["./test/setup-vitest.ts"],
          include: ["test/**/*.test.tsx", ...HOOK_TESTS_NEEDING_DOM],
        },
      },
      {
        extends: true,
        test: {
          name: "node",
          environment: "node",
          include: ["test/**/*.test.ts"],
          exclude: HOOK_TESTS_NEEDING_DOM,
        },
      },
    ],
  },
});
