-- IGDB Game Dump Import
-- Generated: 2026-03-28T23:07:37.093Z
-- Games: 28

BEGIN;

-- Genres
INSERT INTO genres (slug) VALUES ('sport') ON CONFLICT (slug) DO NOTHING;
INSERT INTO genre_translations (genre_id, language_code, name) SELECT id, 'en', 'Sport' FROM genres WHERE slug = 'sport' ON CONFLICT (genre_id, language_code) DO NOTHING;
INSERT INTO genres (slug) VALUES ('arcade') ON CONFLICT (slug) DO NOTHING;
INSERT INTO genre_translations (genre_id, language_code, name) SELECT id, 'en', 'Arcade' FROM genres WHERE slug = 'arcade' ON CONFLICT (genre_id, language_code) DO NOTHING;
INSERT INTO genres (slug) VALUES ('shooter') ON CONFLICT (slug) DO NOTHING;
INSERT INTO genre_translations (genre_id, language_code, name) SELECT id, 'en', 'Shooter' FROM genres WHERE slug = 'shooter' ON CONFLICT (genre_id, language_code) DO NOTHING;
INSERT INTO genres (slug) VALUES ('racing') ON CONFLICT (slug) DO NOTHING;
INSERT INTO genre_translations (genre_id, language_code, name) SELECT id, 'en', 'Racing' FROM genres WHERE slug = 'racing' ON CONFLICT (genre_id, language_code) DO NOTHING;
INSERT INTO genres (slug) VALUES ('pinball') ON CONFLICT (slug) DO NOTHING;
INSERT INTO genre_translations (genre_id, language_code, name) SELECT id, 'en', 'Pinball' FROM genres WHERE slug = 'pinball' ON CONFLICT (genre_id, language_code) DO NOTHING;
INSERT INTO genres (slug) VALUES ('simulator') ON CONFLICT (slug) DO NOTHING;
INSERT INTO genre_translations (genre_id, language_code, name) SELECT id, 'en', 'Simulator' FROM genres WHERE slug = 'simulator' ON CONFLICT (genre_id, language_code) DO NOTHING;
INSERT INTO genres (slug) VALUES ('adventure') ON CONFLICT (slug) DO NOTHING;
INSERT INTO genre_translations (genre_id, language_code, name) SELECT id, 'en', 'Adventure' FROM genres WHERE slug = 'adventure' ON CONFLICT (genre_id, language_code) DO NOTHING;
INSERT INTO genres (slug) VALUES ('indie') ON CONFLICT (slug) DO NOTHING;
INSERT INTO genre_translations (genre_id, language_code, name) SELECT id, 'en', 'Indie' FROM genres WHERE slug = 'indie' ON CONFLICT (genre_id, language_code) DO NOTHING;

-- Companies
INSERT INTO companies (name, slug, company_type) VALUES ('Kee Games', 'kee-games', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Atari', 'atari', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Nintendo', 'nintendo', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Midway Manufacturing', 'midway-manufacturing', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Taito', 'taito', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Leisure and Allied', 'leisure-and-allied', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('RamTeK', 'ramtek', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Sears', 'sears', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Exidy', 'exidy', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Chicago Coin', 'chicago-coin', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('(Archive) Atari Inc.', 'archive-atari-inc', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('General Instrument Microelectronic', 'general-instrument-microelectronic', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Sega Enterprises, Ltd.', 'sega-enterprises-ltd', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('People''s Computer Company', 'peoples-computer-company', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Peter Langston', 'peter-langston', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Namco', 'namco', 'developer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO companies (name, slug, company_type) VALUES ('Cyan Engineering', 'cyan-engineering', 'developer') ON CONFLICT (slug) DO NOTHING;

-- Platforms
INSERT INTO platforms (slug, igdb_id) VALUES ('arcade', 52) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO platform_translations (platform_id, language_code, name) SELECT id, 'en', 'Arcade' FROM platforms WHERE igdb_id = 52 ON CONFLICT (platform_id, language_code) DO NOTHING;
INSERT INTO platforms (slug, igdb_id) VALUES ('plug-play', 377) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO platform_translations (platform_id, language_code, name) SELECT id, 'en', 'Plug & Play' FROM platforms WHERE igdb_id = 377 ON CONFLICT (platform_id, language_code) DO NOTHING;
INSERT INTO platforms (slug, igdb_id) VALUES ('ay-3-8606', 147) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO platform_translations (platform_id, language_code, name) SELECT id, 'en', 'AY-3-8606' FROM platforms WHERE igdb_id = 147 ON CONFLICT (platform_id, language_code) DO NOTHING;
INSERT INTO platforms (slug, igdb_id) VALUES ('plato', 110) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO platform_translations (platform_id, language_code, name) SELECT id, 'en', 'PLATO' FROM platforms WHERE igdb_id = 110 ON CONFLICT (platform_id, language_code) DO NOTHING;
INSERT INTO platforms (slug, igdb_id) VALUES ('hp-2100', 104) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO platform_translations (platform_id, language_code, name) SELECT id, 'en', 'HP 2100' FROM platforms WHERE igdb_id = 104 ON CONFLICT (platform_id, language_code) DO NOTHING;
INSERT INTO platforms (slug, igdb_id) VALUES ('legacy-computer', 409) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO platform_translations (platform_id, language_code, name) SELECT id, 'en', 'Legacy Computer' FROM platforms WHERE igdb_id = 409 ON CONFLICT (platform_id, language_code) DO NOTHING;
INSERT INTO platforms (slug, igdb_id) VALUES ('dos', 13) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO platform_translations (platform_id, language_code, name) SELECT id, 'en', 'DOS' FROM platforms WHERE igdb_id = 13 ON CONFLICT (platform_id, language_code) DO NOTHING;

-- Supported languages
INSERT INTO supported_languages (code, name, native_name) VALUES ('en', 'English', 'English (US)') ON CONFLICT (code) DO NOTHING;

INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('quadrapong', 79040, '1974-03-04', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9oa3.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/scq2jo.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Quadrapong', 'Quadrapong is a four-player version of Pong by Atari Inc. subsidiary Kee Games, and designed by Steve Bristow.

Quadrapong was the first cocktail cabinet arcade video game. The cabinet consists of a woodgrain 35" x 37" cocktail cabinet. Two control paddles are mounted on each side of the cabinet, with a horizontally mounted Zenith television diagonally set in the cabinet.

Two, three, or four players move their paddles to defend their goal area, consisting of openings in the players'' walls. Each player starts with four points, and loses one point each time the ball penetrates their goal. If all four points are lost the player''s paddle is removed and the goal "closes", creating a solid wall and removing the player from the game. The game continues until only one player is left.' FROM games WHERE igdb_id = 79040 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 79040 AND ge.slug = 'sport' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 79040 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 79040 AND c.slug = 'kee-games' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 79040 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 79040 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scq2jo.jpg', 0, true FROM games WHERE igdb_id = 79040 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=0kIzedMXvvI', 'https://img.youtube.com/vi/0kIzedMXvvI/maxresdefault.jpg', 'Gameplay Video', 'trailer', 0, true FROM games WHERE igdb_id = 79040 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 79040 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('wild-gunman--1', 16980, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9i5x.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Wild Gunman', 'Wild Gunman is a game that was first released in arcades in 1974 by Nintendo. The original version of the game featured a 16mm-projection screen that had the player shoot the gunman when his eyes blinked. If he or she did so at the right moment, the gunman would be shot down and killed. If they didn''t, the player would be shot (in the in-game). The arcade was large and was part of the Simulation System that also included Shooting Trainer, which was much less exciting than its dueling counterpart.' FROM games WHERE igdb_id = 16980 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 16980 AND ge.slug = 'shooter' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 16980 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 16980 AND c.slug = 'nintendo' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 16980 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('wheels--1', 170425, '1974-11-01', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9r0y.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/ar3kan.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Wheels', 'Speed Race is a 1974 arcade racing video game developed and manufactured by Taito and released under the titles "Racer" and "Wheels" in North America by distributor Midway Manufacturing in 1975. Designed by Tomohiro Nishikado, the gameplay involves the player using the attached steering wheel to maneuver a car alongside a fast vertical scrolling road. The objective is to score points by driving past other cars without colliding with them; more points are awarded for driving faster. Players must do this under a 90-second time limit, which ends the game when it runs out. The gameplay concepts were adapted from two earlier driving electro-mechanical games: Kasco''s Mini Drive (1958) and Taito''s Super Road 7 (1970).

The original Speed Race and Wheels had an upright arcade cabinet, while Midway''s Racer introduced a sit-down cabinet. Taito released an updated version of Speed Race called Speed Race DX in 1975. Two-player versions followed with Midway''s Wheels II and Taito''s Speed Race Twin.

The game was a worldwide commercial success. Speed Race was a hit in Japan, establishing 100 yen per play as the standard for arcade games there, while Wheels and Wheels II sold 10,000 arcade cabinets in the United States to become the best-selling arcade game of 1975. The Speed Race DX and Wheels versions were also among the top three highest-grossing arcade games of 1976 in Japan and the United States, respectively, while Speed Race DX was Japan''s highest-grossing arcade video game of 1977. The game spawned the Speed Race series of arcade racing games. The game''s use of vertical scrolling was also influential on later games.' FROM games WHERE igdb_id = 170425 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 170425 AND ge.slug = 'racing' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 170425 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 170425 AND c.slug = 'midway-manufacturing' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 170425 AND c.slug = 'taito' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 170425 AND c.slug = 'leisure-and-allied' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 170425 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scwmsu.jpg', 0, true FROM games WHERE igdb_id = 170425 ON CONFLICT DO NOTHING;
INSERT INTO game_artwork (game_id, url, artwork_type, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/ar3kan.jpg', 'promotional', 0, true FROM games WHERE igdb_id = 170425 ON CONFLICT DO NOTHING;
INSERT INTO game_artwork (game_id, url, artwork_type, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/ar3kal.jpg', 'promotional', 1, false FROM games WHERE igdb_id = 170425 ON CONFLICT DO NOTHING;
INSERT INTO game_artwork (game_id, url, artwork_type, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/ar3kam.jpg', 'promotional', 2, false FROM games WHERE igdb_id = 170425 ON CONFLICT DO NOTHING;
INSERT INTO game_artwork (game_id, url, artwork_type, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/ar3kao.jpg', 'promotional', 3, false FROM games WHERE igdb_id = 170425 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=vj0rMaJ592E', 'https://img.youtube.com/vi/vj0rMaJ592E/maxresdefault.jpg', 'Gameplay Video', 'trailer', 0, true FROM games WHERE igdb_id = 170425 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=5jc9_xrD2_M', 'https://img.youtube.com/vi/5jc9_xrD2_M/maxresdefault.jpg', 'Gameplay Video', 'trailer', 1, false FROM games WHERE igdb_id = 170425 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('baseball--10', 171259, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3ud6.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Baseball', NULL FROM games WHERE igdb_id = 171259 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 171259 AND c.slug = 'ramtek' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 171259 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('super-pong', 64120, '1974-02-01', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9oa2.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/scwa2j.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Super Pong', 'Pong with three paddles per player and better ball physics.' FROM games WHERE igdb_id = 64120 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 64120 AND ge.slug = 'sport' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 64120 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 64120 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 64120 AND c.slug = 'sears' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 64120 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 64120 AND p.igdb_id = 377 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scwa2j.jpg', 0, true FROM games WHERE igdb_id = 64120 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('tv-pinball', 171267, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3udb.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'TV Pinball', 'Exidy''s first game, a ball-and-paddle game inspired by pinball mechanics.' FROM games WHERE igdb_id = 171267 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 171267 AND c.slug = 'exidy' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 171267 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('playtime', 170847, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3u46.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Playtime', 'A two-player ball-and-paddle game by Midway.' FROM games WHERE igdb_id = 170847 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 170847 AND c.slug = 'midway-manufacturing' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 170847 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('tv-pingame', 257603, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6t5z.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfbn.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'TV Pingame', 'A pinball game where a ball and paddle are used to knock out bumpers, hit pockets and a moving target at the top of the screen to score points. Keep ball in play by bouncing it back up and knock out all the targets for bonus points.

It has been produced under different names by Chicago Coin, Exidy and Midway Manufacturing Co.' FROM games WHERE igdb_id = 257603 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 257603 AND ge.slug = 'pinball' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 257603 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 257603 AND c.slug = 'exidy' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 257603 AND c.slug = 'chicago-coin' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 257603 AND c.slug = 'midway-manufacturing' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 257603 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfbn.jpg', 0, true FROM games WHERE igdb_id = 257603 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfbo.jpg', 1, false FROM games WHERE igdb_id = 257603 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfbm.jpg', 2, false FROM games WHERE igdb_id = 257603 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfe6.jpg', 3, false FROM games WHERE igdb_id = 257603 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('world-cup--1', 174657, '1974-04-01', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9om2.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'World Cup', 'A soccer-themed ball-and-paddle game by Atari released in conjuction with the 1974 FIFA World Cup held in West Germany. It was the first Atari arcade game to be produced in a cocktail format.' FROM games WHERE igdb_id = 174657 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 174657 AND ge.slug = 'sport' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 174657 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 174657 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('tv-basketball', 16979, '1974-04-01', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/cdzavpwdr4yuelkeifsg.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/vnqpei80chldn4jzj9lp.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'TV Basketball', 'Released in the arcades in april 1974, Basketball was a landmark title, notable for several firsts in video gaming. It was the first basketball video game, the first video game to use sprites, and the first to represent human characters. It is also the first known Japanese-developed game to be released in North America.' FROM games WHERE igdb_id = 16979 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 16979 AND ge.slug = 'sport' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 16979 AND c.slug = 'midway-manufacturing' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 16979 AND c.slug = 'taito' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 16979 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/vnqpei80chldn4jzj9lp.jpg', 0, true FROM games WHERE igdb_id = 16979 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/jpn59st68nmh1qqqhohi.jpg', 1, false FROM games WHERE igdb_id = 16979 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=BMV_meVa7m8', 'https://img.youtube.com/vi/BMV_meVa7m8/maxresdefault.jpg', 'Gameplay video', 'trailer', 0, true FROM games WHERE igdb_id = 16979 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('world-cup-football', 130764, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7lh2.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/scq2jq.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'World Cup Football', 'Pong variant emulating foosball.' FROM games WHERE igdb_id = 130764 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 130764 AND ge.slug = 'sport' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 130764 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 130764 AND c.slug = 'archive-atari-inc' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 130764 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scq2jq.jpg', 0, true FROM games WHERE igdb_id = 130764 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 130764 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('pin-pong', 18155, '1974-10-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6t62.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfbr.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Pin Pong', 'The first pinball videogame.

It is a simple black and white pinball table with basic gravity simulation and controllable pinball flippers. Developed by Terry Niksch and Harold Lee for Atari.' FROM games WHERE igdb_id = 18155 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 18155 AND ge.slug = 'simulator' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 18155 AND ge.slug = 'pinball' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 18155 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 18155 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 18155 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfbr.jpg', 0, true FROM games WHERE igdb_id = 18155 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfbs.jpg', 1, false FROM games WHERE igdb_id = 18155 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=Jw_FzPK3ZQY', 'https://img.youtube.com/vi/Jw_FzPK3ZQY/maxresdefault.jpg', 'Gameplay Video', 'trailer', 0, true FROM games WHERE igdb_id = 18155 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('wipe-out', 18160, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/tlfgw1mnogzidxob07zl.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/scq2k3.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Wipe Out', 'A RamTeK-clone of the Quadrapong-concept.' FROM games WHERE igdb_id = 18160 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 18160 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 18160 AND c.slug = 'ramtek' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 18160 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scq2k3.jpg', 0, true FROM games WHERE igdb_id = 18160 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=VXMFPAffARk', 'https://img.youtube.com/vi/VXMFPAffARk/maxresdefault.jpg', 'Gameplay Video', 'trailer', 0, true FROM games WHERE igdb_id = 18160 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 18160 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('rebound', 16977, '1974-02-13', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6t8v.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/sc5j39.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Rebound', 'Rebound is a 2 player arcade game that simulates a volleyball match by having players volley a ball back and forth over a net with their paddles.' FROM games WHERE igdb_id = 16977 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 16977 AND ge.slug = 'sport' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 16977 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 16977 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 16977 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/sc5j39.jpg', 0, true FROM games WHERE igdb_id = 16977 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 16977 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('clean-sweep', 18159, '1974-05-01', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/t9f5larhhlpsokrxok7h.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/rhioo0oqowyx8dlqbnin.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Clean Sweep', 'Clean Sweep is a variation of the popular Pong theme of the time. It looks like a mix between Breakout and Pac-Man, but it was created before both of these games.' FROM games WHERE igdb_id = 18159 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 18159 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 18159 AND c.slug = 'general-instrument-microelectronic' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 18159 AND c.slug = 'ramtek' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 18159 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 18159 AND p.igdb_id = 147 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/rhioo0oqowyx8dlqbnin.jpg', 0, true FROM games WHERE igdb_id = 18159 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=DRzbgzKSdeo', 'https://img.youtube.com/vi/DRzbgzKSdeo/maxresdefault.jpg', 'Gameplay Video', 'trailer', 0, true FROM games WHERE igdb_id = 18159 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 18159 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('goal-kick', 171849, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3usl.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Goal Kick', 'A ball-and-paddle game from Sega.' FROM games WHERE igdb_id = 171849 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 171849 AND c.slug = 'sega-enterprises-ltd' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 171849 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('ball-park', 91375, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3u0j.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Ball Park', 'A licensed version of Ramtek''s game Baseball.' FROM games WHERE igdb_id = 91375 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 91375 AND c.slug = 'midway-manufacturing' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 91375 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('spasim', 11512, '1974-03-01', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6s8t.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Spasim', 'Spasim (abbreviation of ''space simulation'') was a 32-player 3D networked computer game by Jim Bowery involving 4 planetary systems with up to 8 players per planetary system, released in March 1, 1974. Jim Bowery claims that it is the very first 3D multiplayer game and has offered reward of US $500 to anyone who could document an example of a multiplayer 3D virtual reality game prior to Spasim. In Spasim the players flew around in space and to each other they appeared as wire-frame space ships. Their positions were updated about every second.

The game was played on the PLATO computer system, and was heavily influenced by another PLATO space multiplayer game Empire. Later 3D multiplayer games on the PLATO network included airace by Silas Warner that evolved into airfight (by Brand Fortner), and then spawned Panther by John Edo Haefeli at NW University. Atari, Inc had a PLATO account and Panther is said to be the origin of Battlezone while airfight led up to Sublogic''s Microsoft Flight Simulator. Also, Panther was developed into the more sophisticated Panzer by the US Army.' FROM games WHERE igdb_id = 11512 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 11512 AND ge.slug = 'shooter' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 11512 AND ge.slug = 'simulator' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 11512 AND p.igdb_id = 110 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('balloon-gun', 63847, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/l06dpceeu5gcie146jg2.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Balloon Gun', 'Released by Sega in 1974, it was an early first-person light-gun shooter video game, featuring both single-player and multi-player modes.' FROM games WHERE igdb_id = 63847 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 63847 AND ge.slug = 'shooter' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 63847 AND c.slug = 'sega-enterprises-ltd' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 63847 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('star-trader', 16976, '1974-01-01', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6k9y.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/ch2fsctzm5fmbn9gacwt.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Star Trader', 'Star Trader is a 1974 video game and an early example of the space trading genre. Seemingly based on Isaac Asimov’s Foundation series of novels, Star Trader presents a star map of the galaxy in which the players move about and make money from trading and establishing trading routes. The players travel about the star map buying and selling six types of merchandise: uranium, metals, gems, software, heavy equipment, and medicine.' FROM games WHERE igdb_id = 16976 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 16976 AND ge.slug = 'simulator' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 16976 AND c.slug = 'peoples-computer-company' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 16976 AND p.igdb_id = 104 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/ch2fsctzm5fmbn9gacwt.jpg', 0, true FROM games WHERE igdb_id = 16976 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('touch-me', 225597, '1974-06-11', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5ry3.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/sctdo8.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Touch Me', 'Touch me challenges the player to remember the sequence of sight and sound, and correctly repeat the pattern. The drop of the quarter in the top-mounted acceptor activates the computer to present a single-tone sound. When the sound occurs, the corresponding button lights to give a visual clue. Then the game pauses long enough for the player to "confirm" the sound to the computer by pressing the same button that lit. Oops! Wrong button? ERROR number one… and a lighted window tells the player he''s goofed. Then another chance… the sound and lighted button are repeated by the computer. Another pause … right! You''ve hit the right button(s) in the right sequence, and the game goes on to another sound sequence. Every correct player response adds an additional sound/note to the sequence. "Beep – beep – bloop – beep – bloop" … Did you correctly repeat those sounds when the buttons lit? Sorry, only three errors per game. You''ll have to insert another 25¢ and try again!' FROM games WHERE igdb_id = 225597 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 225597 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 225597 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 225597 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/sctdo8.jpg', 0, true FROM games WHERE igdb_id = 225597 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/sctdo9.jpg', 1, false FROM games WHERE igdb_id = 225597 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('wander--1', 80032, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6zci.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/sco2xw.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Wander', 'An interactive fiction game / interactive fiction creation utility pre-dating the release of Colossal Cave Adventure.' FROM games WHERE igdb_id = 80032 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 80032 AND ge.slug = 'adventure' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 80032 AND ge.slug = 'indie' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 80032 AND c.slug = 'peter-langston' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 80032 AND p.igdb_id = 409 ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 80032 AND p.igdb_id = 13 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/sco2xw.jpg', 0, true FROM games WHERE igdb_id = 80032 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/sco2xx.jpg', 1, false FROM games WHERE igdb_id = 80032 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/sco2xy.jpg', 2, false FROM games WHERE igdb_id = 80032 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/sco2xz.jpg', 3, false FROM games WHERE igdb_id = 80032 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 80032 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('airfight', 67637, '1974-09-30', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7w05.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/scr4ay.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Airfight', 'Airfight is an early 3D graphics-based multi-user flight simulator, created on the University of Illinois Urbana-Champaign (UIUC) Control Data Corporation (CDC) PLATO system.

The software was the first ever 3D flight simulator and the first multi-player flight simulator. The first version was developed by Brand Fortner with Kevin Gorey in the summer of 1974. After its release, it became the most popular game on PLATO until Empire became more popular. This software probably inspired the UIUC student Bruce Artwick to start the company Sublogic, which was acquired and later became Microsoft Flight Simulator.' FROM games WHERE igdb_id = 67637 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 67637 AND ge.slug = 'simulator' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 67637 AND p.igdb_id = 110 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scr4ay.jpg', 0, true FROM games WHERE igdb_id = 67637 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=jDkQFYWcSIg', 'https://img.youtube.com/vi/jDkQFYWcSIg/maxresdefault.jpg', 'Gameplay Video', 'trailer', 0, true FROM games WHERE igdb_id = 67637 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('gran-trak-10', 7429, '1974-03-15', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co972h.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/ar38rd.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Gran Trak 10', 'Gran Trak 10 was a single-player racing arcade game released by Atari in 1974. The player raced against the clock, accumulating as many points as possible. Primitive diode-based ROM was used to store the sprites for the car, score and game timer, and the race track. The game''s controls — steering wheel, four-position gear shifter, and accelerator and brake foot pedals — were also all firsts for arcade games.' FROM games WHERE igdb_id = 7429 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 7429 AND ge.slug = 'racing' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 7429 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 7429 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 7429 AND c.slug = 'namco' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 7429 AND c.slug = 'cyan-engineering' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 7429 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scphxq.jpg', 0, true FROM games WHERE igdb_id = 7429 ON CONFLICT DO NOTHING;
INSERT INTO game_artwork (game_id, url, artwork_type, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/ar38rd.jpg', 'promotional', 0, true FROM games WHERE igdb_id = 7429 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=KYcNvAAeu6k', 'https://img.youtube.com/vi/KYcNvAAeu6k/maxresdefault.jpg', 'Gameplay Video', 'trailer', 0, true FROM games WHERE igdb_id = 7429 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 7429 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('qwak--1', 11511, '1974-03-04', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6t8y.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfhn.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Qwak!', 'Qwak! is a duck hunting light gun shooter arcade video game developed by Atari and released in 1974.

In the game, ducks fly one at a time across the screen, and the player shoots at them using a light gun attached to the game cabinet. The player gets three shots per duck; ducks change direction away from missed shots and fall to the bottom of the screen when hit. A screen overlay adds images of reeds and a tree branch, and an image of a duck is added to a row at the top of the screen whenever a duck is hit. Games continue until a time limit, set by the machine operator, is reached.

Qwak! is most likely the inspiration for the 1984 Nintendo Entertainment System light gun game Duck Hunt.' FROM games WHERE igdb_id = 11511 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 11511 AND ge.slug = 'shooter' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 11511 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 11511 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 11511 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfhn.jpg', 0, true FROM games WHERE igdb_id = 11511 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/scnfho.jpg', 1, false FROM games WHERE igdb_id = 11511 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 11511 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('tank', 7428, '1974-11-05', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6wr7.jpg', 'https://images.igdb.com/igdb/image/upload/t_1080p/ogwxn1c0ag7nfruk28by.jpg', NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Tank', 'Players move their tanks through a maze on screen, avoiding mines and shooting each other. The tanks are controlled by two joysticks in a dual configuration. Pushing both joysticks will move the player''s tank forward, and pulling them both back causes the tank to stop. Moving the right joystick forward while pulling the left joystick back will cause the tank to turn right, while reversing the motion will cause the tank to turn left. The players are represented by one black and one white tank sprite, and mines are denoted by an "X". Points are scored by shooting the opponent or when a player runs over a mine; the player with the highest score at the end of the time limit wins the game.

Tank was also one of very few games to be ported onto 1st generation consoles, usually under the title "Tank Battle".' FROM games WHERE igdb_id = 7428 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 7428 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 7428 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 7428 AND c.slug = 'kee-games' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 7428 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_screenshots (game_id, url, display_order, is_featured) SELECT id, 'https://images.igdb.com/igdb/image/upload/t_1080p/ogwxn1c0ag7nfruk28by.jpg', 0, true FROM games WHERE igdb_id = 7428 ON CONFLICT DO NOTHING;
INSERT INTO game_videos (game_id, url, thumbnail_url, title, video_type, display_order, is_featured) SELECT id, 'https://www.youtube.com/watch?v=3OsBUzYBJgU', 'https://img.youtube.com/vi/3OsBUzYBJgU/maxresdefault.jpg', 'Gameplay video', 'trailer', 0, true FROM games WHERE igdb_id = 7428 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 7428 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('gran-trak-20', 174658, '1974-08-01', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3xv3.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Gran Trak 20', 'Gran Trak 20 is the follow-up to Gran Trak 10. Unlike the original game it allows two people to race each other, a significant innovation since neither game features computer-controlled cars.' FROM games WHERE igdb_id = 174658 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 174658 AND ge.slug = 'racing' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 174658 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 174658 AND c.slug = 'atari' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 174658 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;
INSERT INTO game_languages (game_id, language_code, language_name, has_audio, has_subtitles, has_interface) SELECT id, 'en', 'English', false, false, true FROM games WHERE igdb_id = 174658 ON CONFLICT DO NOTHING;
INSERT INTO games (slug, igdb_id, release_date, metascore, cover_image_url, background_image_url, last_synced_at) VALUES ('attack-ufo', 172546, '1974-12-31', NULL, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3w5h.jpg', NULL, NOW()) ON CONFLICT (igdb_id) DO NOTHING;
INSERT INTO game_translations (game_id, language_code, title, description) SELECT id, 'en', 'Attack UFO', 'The player controls guided missiles shot from the bottom of the screen and tries to steer them into the attacking U.F.O.s' FROM games WHERE igdb_id = 172546 ON CONFLICT (game_id, language_code) DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 172546 AND ge.slug = 'shooter' ON CONFLICT DO NOTHING;
INSERT INTO game_genres (game_id, genre_id) SELECT g.id, ge.id FROM games g, genres ge WHERE g.igdb_id = 172546 AND ge.slug = 'arcade' ON CONFLICT DO NOTHING;
INSERT INTO game_companies (game_id, company_id, role, is_primary) SELECT g.id, c.id, 'developer', false FROM games g, companies c WHERE g.igdb_id = 172546 AND c.slug = 'taito' ON CONFLICT DO NOTHING;
INSERT INTO game_platforms (game_id, platform_id) SELECT g.id, p.id FROM games g, platforms p WHERE g.igdb_id = 172546 AND p.igdb_id = 52 ON CONFLICT DO NOTHING;

COMMIT;
